"""
core/evidence_hashing.py — Forensic Evidence Hashing Framework

DFIR-grade hashing for evidence files captured/generated by the honeypot
suite (malware samples, report exports, STIX bundles, session
recordings). Implements:

  - calculate_hashes(file_path)   → streamed, chunked SHA256/SHA1/MD5
  - verify_hash(file_path, stored_sha256) → bool, recomputes + compares
  - save_hash_metadata(evidence_id) → re-hash an existing Evidence row
    and persist the refreshed values + verification result
  - register_evidence_file(...)   → the actual hook point other modules
    call right after writing a file to disk, to create the initial
    Evidence row (this is what "automatically calculate hashes whenever
    a new evidence file is created/uploaded/exported/collected" means
    in practice — see the integration points in malware_capture.py,
    report_generator.py, and stix_export.py)

Design constraints honored:
  - Files are streamed in fixed-size chunks (CHUNK_SIZE) — never
    `f.read()` the whole file into memory, so a multi-GB capture or
    export doesn't blow up process memory.
  - Missing/corrupt/unreadable files are handled as recoverable errors
    (logged, returns a result dict with `error` set), never raised as
    an uncaught exception that could crash a calling honeypot service.
  - SHA256 is mandatory and always computed; SHA1/MD5 are computed in
    the same single pass (one read loop, three running digests) rather
    than three separate file reads, since they're optional-but-cheap to
    include alongside the mandatory SHA256 pass.
  - MD5/SHA1 are flagged `usedforsecurity=False` — same rationale as
    the existing malware_capture.py hashing: these identify/fingerprint
    files (e.g. cross-referencing VirusTotal, NSRL, or other hash
    databases that still report MD5/SHA1 alongside SHA256), not a
    cryptographic integrity guarantee. SHA256 carries that guarantee.

Logging format (matches the requested [EVIDENCE_HASH] block format):
    [EVIDENCE_HASH]
    File: sample.bin
    SHA256: <hex>
    Status: VERIFIED | UNVERIFIED | MISMATCH | ERROR
"""

import os
import hashlib
import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger("EvidenceHashing")

CHUNK_SIZE = 1024 * 1024   # 1 MiB per read — large-file-safe, no full-file load


# ── Core hashing ────────────────────────────────────────────────────

def calculate_hashes(file_path: str, include_md5: bool = True,
                     include_sha1: bool = True) -> dict:
    """
    Stream `file_path` in CHUNK_SIZE-byte chunks and compute SHA256
    (always) plus SHA1/MD5 (optional, on by default) in a single pass.

    Returns:
        {
            "file_path": str,
            "file_size": int,
            "sha256": str,
            "sha1": str | None,
            "md5": str | None,
            "calculated_at": ISO8601 str,
            "error": str | None,
        }

    Never raises for missing/unreadable/corrupt files — returns a
    result dict with "error" set and all hash fields None instead, so
    callers (honeypot services, the API layer) don't need a try/except
    around every call site.
    """
    result = {
        "file_path": file_path,
        "file_size": None,
        "sha256": None,
        "sha1": None,
        "md5": None,
        "calculated_at": datetime.utcnow().isoformat(),
        "error": None,
    }

    if not file_path:
        result["error"] = "No file path provided"
        logger.error("[EVIDENCE_HASH]\nFile: <none>\nStatus: ERROR (no path provided)")
        return result

    if not os.path.exists(file_path):
        result["error"] = f"File not found: {file_path}"
        logger.error(f"[EVIDENCE_HASH]\nFile: {os.path.basename(file_path)}\n"
                    f"Status: ERROR (file not found)")
        return result

    if not os.path.isfile(file_path):
        result["error"] = f"Path is not a regular file: {file_path}"
        logger.error(f"[EVIDENCE_HASH]\nFile: {os.path.basename(file_path)}\n"
                    f"Status: ERROR (not a regular file)")
        return result

    sha256 = hashlib.sha256()
    sha1   = hashlib.sha1(usedforsecurity=False) if include_sha1 else None
    md5    = hashlib.md5(usedforsecurity=False) if include_md5 else None

    bytes_read = 0
    try:
        with open(file_path, "rb") as f:
            while True:
                chunk = f.read(CHUNK_SIZE)
                if not chunk:
                    break
                sha256.update(chunk)
                if sha1 is not None:
                    sha1.update(chunk)
                if md5 is not None:
                    md5.update(chunk)
                bytes_read += len(chunk)
    except PermissionError as e:
        result["error"] = f"Permission denied reading {file_path}: {e}"
        logger.error(f"[EVIDENCE_HASH]\nFile: {os.path.basename(file_path)}\n"
                    f"Status: ERROR (permission denied)")
        return result
    except OSError as e:
        # Covers corrupt/unreadable filesystem entries, I/O errors
        # mid-read (e.g. disk failure, truncated network mount), etc.
        result["error"] = f"I/O error reading {file_path}: {e}"
        logger.error(f"[EVIDENCE_HASH]\nFile: {os.path.basename(file_path)}\n"
                    f"Status: ERROR (I/O error: {e})")
        return result

    result["file_size"] = bytes_read
    result["sha256"] = sha256.hexdigest()
    result["sha1"]   = sha1.hexdigest() if sha1 is not None else None
    result["md5"]    = md5.hexdigest() if md5 is not None else None

    logger.info(f"[EVIDENCE_HASH]\nFile: {os.path.basename(file_path)}\n"
                f"SHA256: {result['sha256']}\nStatus: HASHED")
    return result


def verify_hash(file_path: str, stored_sha256: str) -> bool:
    """
    Recompute SHA256 for `file_path` and compare against
    `stored_sha256`. Returns True only on an exact match; returns
    False (not an exception) for a mismatch OR for any read error
    (missing file, permission denied, corrupt file) — a file that
    can't be re-hashed can't be verified, which is itself a
    verification failure from a chain-of-custody standpoint.
    """
    if not stored_sha256:
        logger.error(f"[EVIDENCE_HASH]\nFile: {os.path.basename(file_path) if file_path else '<none>'}\n"
                    f"Status: ERROR (no stored hash to compare against)")
        return False

    result = calculate_hashes(file_path, include_md5=False, include_sha1=False)

    if result["error"]:
        logger.error(f"[EVIDENCE_HASH]\nFile: {os.path.basename(file_path)}\n"
                    f"SHA256: <unavailable>\nStatus: ERROR ({result['error']})")
        return False

    is_match = result["sha256"].lower() == stored_sha256.lower()
    status = "VERIFIED" if is_match else "MISMATCH"
    log_fn = logger.info if is_match else logger.warning
    log_fn(f"[EVIDENCE_HASH]\nFile: {os.path.basename(file_path)}\n"
          f"SHA256: {result['sha256']}\nStatus: {status}")

    return is_match


# ── Database integration ─────────────────────────────────────────────

def register_evidence_file(file_path: str, source_type: str = "manual",
                           source_id: Optional[str] = None,
                           include_md5: bool = True,
                           include_sha1: bool = True) -> Optional[dict]:
    """
    THE hook point other modules call right after writing a new
    evidence file to disk — malware_capture.capture(),
    report_generator.generate_report(), stix_export.export_json(),
    session_recorder's save path, etc.

    Computes hashes and creates (or updates, if file_path already has
    a row — re-registering an existing path refreshes its hashes
    rather than erroring) the corresponding `Evidence` database row.

    Returns the Evidence row as a dict, or None if the DB layer isn't
    available (e.g. called before database.init_db()) or hashing
    failed — callers should treat None as "couldn't register, but the
    underlying file operation itself should not be rolled back over
    this," consistent with how run.py's other DB-write patches
    swallow DB errors rather than propagating them into the honeypot's
    core capture/export logic.
    """
    hashes = calculate_hashes(file_path, include_md5=include_md5, include_sha1=include_sha1)
    if hashes["error"]:
        logger.error(f"register_evidence_file: hashing failed for {file_path}: {hashes['error']}")
        return None

    try:
        from database import DbSession, Evidence
    except Exception as e:
        logger.warning(f"register_evidence_file: database layer unavailable, "
                       f"hash computed but not persisted: {e}")
        return hashes

    try:
        with DbSession() as s:
            row = s.query(Evidence).filter(Evidence.file_path == file_path).first()
            now = datetime.utcnow()
            is_new = row is None
            if row is None:
                row = Evidence(
                    file_name=os.path.basename(file_path),
                    file_path=file_path,
                    file_size=hashes["file_size"],
                    source_type=source_type,
                    source_id=str(source_id) if source_id is not None else None,
                    sha256_hash=hashes["sha256"],
                    sha1_hash=hashes["sha1"],
                    md5_hash=hashes["md5"],
                    hash_created_at=now,
                    hash_verified=True,          # freshly computed == trivially self-consistent
                    last_verified_at=now,
                    verification_count=1,
                    created_at=now,
                )
                s.add(row)
            else:
                row.file_size = hashes["file_size"]
                row.sha256_hash = hashes["sha256"]
                row.sha1_hash = hashes["sha1"]
                row.md5_hash = hashes["md5"]
                row.hash_created_at = now
                row.hash_verified = True
                row.last_verified_at = now
                row.verification_count = (row.verification_count or 0) + 1
            s.commit()
            result = row.to_json_safe()
            evidence_id_val = row.id

        # Chain of Custody — fire after the DB session is committed and
        # closed so the CoC insert can open its own clean session.
        try:
            from core.chain_of_custody import record_event
            if is_new:
                record_event(
                    evidence_id=evidence_id_val,
                    action="CREATED",
                    performed_by="system",
                    reason=f"Evidence registered via {source_type}",
                )
            record_event(
                evidence_id=evidence_id_val,
                action="HASHED",
                performed_by="system",
                reason=f"SHA256 computed: {hashes['sha256'][:16]}...",
            )
        except Exception:
            pass   # CoC failure must never block evidence registration

        # Phase 1C — auto-sign the SHA-256 if enabled in config
        try:
            _auto_sign_evidence(evidence_id_val, hashes["sha256"])
        except Exception:
            pass   # signing failure must never block registration

        # Phase 1D — create immutable manifest after hash+sign complete
        try:
            _auto_create_manifest(evidence_id_val)
        except Exception:
            pass   # manifest failure must never block registration

        return result
    except Exception as e:
        logger.error(f"register_evidence_file: DB write failed for {file_path}: {e}")
        return hashes


def save_hash_metadata(evidence_id: int) -> Optional[dict]:
    """
    Re-hash the file backing an existing Evidence row, persist the
    refreshed sha256_hash/sha1_hash/md5_hash/hash_created_at, and set
    hash_verified based on whether the recomputed SHA256 still matches
    what was previously stored (True on first-ever hash, or if the
    freshly recomputed value matches the prior one; False if the file
    on disk has changed since it was last hashed — which, for a
    forensic evidence file, IS the integrity signal this function
    exists to surface).

    Returns the updated Evidence row as a dict, or None if the row
    doesn't exist or the DB layer is unavailable.
    """
    try:
        from database import DbSession, Evidence
    except Exception as e:
        logger.warning(f"save_hash_metadata: database layer unavailable: {e}")
        return None

    with DbSession() as s:
        row = s.query(Evidence).filter(Evidence.id == evidence_id).first()
        if row is None:
            logger.error(f"save_hash_metadata: no Evidence row with id={evidence_id}")
            return None

        previous_sha256 = row.sha256_hash
        hashes = calculate_hashes(row.file_path)

        now = datetime.utcnow()
        row.hash_created_at = now
        row.last_verified_at = now
        row.verification_count = (row.verification_count or 0) + 1

        if hashes["error"]:
            row.hash_verified = False
            row.notes = (row.notes or "") + f" | re-hash error at {now.isoformat()}: {hashes['error']}"
            s.commit()
            logger.error(f"[EVIDENCE_HASH]\nFile: {row.file_name}\n"
                        f"SHA256: {previous_sha256 or '<none>'}\nStatus: ERROR ({hashes['error']})")
            try:
                from core.chain_of_custody import record_event
                record_event(evidence_id, "HASHED", performed_by="system",
                             reason=f"Re-hash failed: {hashes['error']}", status="FAILED")
            except Exception:
                pass
            return row.to_json_safe()

        row.sha256_hash = hashes["sha256"]
        row.sha1_hash = hashes["sha1"]
        row.md5_hash = hashes["md5"]
        row.file_size = hashes["file_size"]

        if previous_sha256:
            row.hash_verified = (hashes["sha256"].lower() == previous_sha256.lower())
        else:
            row.hash_verified = True   # nothing to compare against yet — first hash is trivially "verified"

        s.commit()

        status = "VERIFIED" if row.hash_verified else "MISMATCH"
        log_fn = logger.info if row.hash_verified else logger.warning
        log_fn(f"[EVIDENCE_HASH]\nFile: {row.file_name}\n"
              f"SHA256: {row.sha256_hash}\nStatus: {status}")

        coc_status = "OK" if row.hash_verified else "FAILED"
        coc_reason = (
            f"SHA256 re-hashed: {row.sha256_hash[:16]}..."
            if row.hash_verified
            else f"Hash mismatch: stored={previous_sha256[:16]}... computed={row.sha256_hash[:16]}..."
        )
        try:
            from core.chain_of_custody import record_event
            record_event(evidence_id, "HASHED", performed_by="system",
                         reason=coc_reason, status=coc_status)
        except Exception:
            pass

        return row.to_json_safe()


def verify_evidence_by_id(evidence_id: int) -> Optional[dict]:
    """
    Convenience wrapper used by the API endpoint
    (GET /api/evidence/<id>/hash): looks up the Evidence row, re-runs
    verify_hash() against its stored sha256_hash, updates
    hash_verified/last_verified_at/verification_count, and returns the
    row as a dict — without overwriting the hash values themselves
    (unlike save_hash_metadata, which refreshes the stored hash; this
    function only checks the existing one).
    """
    try:
        from database import DbSession, Evidence
    except Exception as e:
        logger.warning(f"verify_evidence_by_id: database layer unavailable: {e}")
        return None

    with DbSession() as s:
        row = s.query(Evidence).filter(Evidence.id == evidence_id).first()
        if row is None:
            return None

        is_valid = verify_hash(row.file_path, row.sha256_hash)
        row.hash_verified = is_valid
        row.last_verified_at = datetime.utcnow()
        row.verification_count = (row.verification_count or 0) + 1
        s.commit()
        result = row.to_json_safe()

    try:
        from core.chain_of_custody import record_event
        record_event(
            evidence_id=evidence_id,
            action="VERIFIED",
            performed_by="system",
            reason="SHA256 integrity check" + (" passed" if is_valid else " FAILED — hash mismatch"),
            status="OK" if is_valid else "FAILED",
        )
    except Exception:
        pass

    return result


# ── Phase 1C signing integration ─────────────────────────────

def _auto_sign_evidence(evidence_id: int, sha256_hex: str) -> None:
    """
    Auto-sign hook called by register_evidence_file when
    config.yaml signing.auto_sign is true.  Silently skips when the
    signing module or DB layer is unavailable, so removing the
    cryptography package never crashes the capture pipeline.
    """
    try:
        from config_loader import cfg
        if not cfg.get("signing.auto_sign", True):
            return
        auto_generate = cfg.get("signing.auto_generate_key", True)
    except Exception:
        auto_generate = True

    try:
        from core.evidence_signing import sign_hash, load_keys, generate_keypair
        from config_loader import cfg
        alg = cfg.get("signing.algorithm", "ed25519")
    except Exception:
        return

    # Generate a keypair on first run if none exists and auto_generate is on
    if load_keys() is None:
        if not auto_generate:
            logger.debug("Auto-sign skipped: no active key and auto_generate_key is false")
            return
        generate_keypair(alg)

    sign_hash(sha256_hex, evidence_id=evidence_id, performed_by="system")


def _auto_create_manifest(evidence_id: int) -> None:
    """
    Auto-manifest hook called by register_evidence_file after Phase 1C
    signing completes.  Silently skips if manifest already exists or if
    the signing row is not yet present (e.g. signing disabled).
    Never raises — must not crash the capture pipeline.
    """
    try:
        from core.evidence_manifest import create_manifest, manifest_exists
        if manifest_exists(evidence_id):
            return
        create_manifest(evidence_id, performed_by="system")
    except Exception as e:
        logger.debug(f"_auto_create_manifest({evidence_id}) skipped: {e}")
